"""
====================================================================
File: 03_messages.py
Repository: AI-Engineer-Cookbook
Topic: LangChain Messages
====================================================================

Description
-----------
Messages are the standard communication format used by chat models.

Instead of passing plain text, chat models exchange
System, Human, AI and Tool messages.

Official Documentation
----------------------
https://python.langchain.com/docs/concepts/messages/
"""

####################################################################
# HumanMessage
####################################################################

# Package
# -------
# langchain-core

# Install
# -------
# pip install langchain

from langchain_core.messages import HumanMessage

# Purpose
# -------
# Represents a message sent by the user.

# When to Use
# -----------
# ✔ Chatbots
# ✔ Agents
# ✔ Testing chat models

# Example

# message = HumanMessage(
#     content="Explain Kubernetes."
# )

# Interview Questions
# -------------------
# Q. What is a HumanMessage?
#
# Represents user input to the LLM.

# Documentation
# -------------
# https://python.langchain.com/docs/concepts/messages/


####################################################################
# AIMessage
####################################################################

from langchain_core.messages import AIMessage

# Purpose
# -------
# Represents a response generated by the AI model.

# Example

# response = AIMessage(
#     content="Kubernetes is a container orchestration platform."
# )

# Interview Questions
# -------------------
# Q. What is AIMessage?
#
# Represents the model's response.


####################################################################
# SystemMessage
####################################################################

from langchain_core.messages import SystemMessage

# Purpose
# -------
# Gives high-level instructions to the LLM.

# When to Use
# -----------
# ✔ Define assistant behavior
# ✔ Set rules
# ✔ Restrict responses

# Example

# system = SystemMessage(
#     content="You are an expert DevOps Engineer."
# )

# Interview Questions
# -------------------
# Q. Why use SystemMessage?
#
# It controls the model's behavior before
# any user interaction.


####################################################################
# ToolMessage
####################################################################

from langchain_core.messages import ToolMessage

# Purpose
# -------
# Represents the result returned by a tool.

# When to Use
# -----------
# ✔ Agents
# ✔ Tool Calling
# ✔ Function Calling

# Example

# tool_message = ToolMessage(
#     content="Docker container restarted successfully.",
#     tool_call_id="call_123"
# )

# Interview Questions
# -------------------
# Q. Why is ToolMessage needed?
#
# It sends tool execution results back to the LLM.


####################################################################
# FunctionMessage
####################################################################

from langchain_core.messages import FunctionMessage

# Purpose
# -------
# Represents the output of a function.
#
# NOTE:
# Older versions of LangChain/OpenAI APIs used this.
# Modern applications typically use ToolMessage instead.

# Example

# function_message = FunctionMessage(
#     name="weather",
#     content="28°C"
# )


####################################################################
# RemoveMessage
####################################################################

from langchain_core.messages import RemoveMessage

# Purpose
# -------
# Removes messages from conversation history.

# When to Use
# -----------
# ✔ Memory Management
# ✔ LangGraph
# ✔ State Updates

# Example

# remove = RemoveMessage(
#     id="message_id"
# )

# Interview Questions
# -------------------
# Q. Why remove messages?
#
# To reduce context size or update conversation state.


####################################################################
# AnyMessage
####################################################################

from langchain_core.messages import AnyMessage

# Purpose
# -------
# Generic type representing any message.

# Possible Types
# --------------
# HumanMessage
# AIMessage
# SystemMessage
# ToolMessage
# FunctionMessage

# Example

# def process(messages: list[AnyMessage]):
#     pass

# Interview Questions
# -------------------
# Q. Why use AnyMessage?
#
# Useful for type hints when working with
# multiple message types.


####################################################################
# Utility Functions
####################################################################

from langchain_core.messages import (
    messages_to_dict,
    messages_from_dict,
)

# Purpose
# -------
# Convert messages to dictionaries and back.

# Example

# messages = [
#     HumanMessage(content="Hello"),
#     AIMessage(content="Hi!")
# ]
#
# data = messages_to_dict(messages)
#
# restored = messages_from_dict(data)

# Interview Questions
# -------------------
# Q. Why serialize messages?
#
# To store them in databases,
# Redis, PostgreSQL or files.


####################################################################
# Summary
####################################################################

# HumanMessage
# ------------
# User input.

# AIMessage
# ---------
# LLM response.

# SystemMessage
# -------------
# AI instructions.

# ToolMessage
# -----------
# Tool execution result.

# FunctionMessage
# ---------------
# Legacy function response.

# RemoveMessage
# -------------
# Delete messages from state.

# AnyMessage
# ----------
# Generic message type.

# messages_to_dict()
# ------------------
# Serialize messages.

# messages_from_dict()
# --------------------
# Deserialize messages.